# ⚠️本配置仅适用于Stash，Clash(Premium)内核不可使用本配置
# 本配置，解决DNS泄露，无分流群组，且为自用!
# 另外，就是新功能的尝鲜，如有问题，还请使用 Awesome.yaml 稳定版
###########################################################
# @created: 2023-04-07
# @update 2023-04-07
# @source https://github.com/NewHugo/Stash
###########################################################
# 参考配置：
# https://stash.wiki
###########################################################
# autocorrect-disable
